# Generated by Django 3.2.3 on 2021-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('health_condition', models.CharField(max_length=200)),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescriptions')),
            ],
        ),
    ]
