# Generated by Django 3.2.3 on 2021-05-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phoneno',
            new_name='phone_number',
        ),
    ]
