# Generated by Django 3.2.3 on 2021-06-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointmentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentemail',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appointmentemail',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
